version: '3.1'
services:
  ewm-service:
    build: explore-with-me-main-server
    image: explore-with-me-main-server-image
    container_name: "explore-main-cont"
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - db
    environment:
      - EXPLORE-WITH-ME-STAT-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore
      - POSTGRES_DB=explore
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password

  stats-server:
    build: explore-with-me-stat-server
    image: explore-with-me-stat-server-image
    container_name: "explore-stat-cont"
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore
      - POSTGRES_DB=explore
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password

  db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password