CREATE TABLE IF NOT EXISTS users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR                                  NOT NULL,
    email VARCHAR                                  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS location
(
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat decimal,
    lon decimal,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR,
    description        VARCHAR,
    category_id        INTEGER references category (id),
    annotation         varchar,
    initiator          integer references users (id),
    date_create        timestamp,
    date_published     timestamp,
    date_event         timestamp,
    location_id        INTEGER references location (id),
    paid               boolean,
    participant_limit  integer,
    state              varchar,
    request_moderation boolean,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS request
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_create  timestamp,
    event_id     integer references event (id),
    requestor_id integer references users (id),
    status       varchar,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean,
    title  varchar,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_to_compilation
(
    event_id       integer references event (id),
    compilation_id integer references compilations (id)
);

CREATE TABLE if not exists comments
(
    id             integer generated by default as identity not null,
    comment        varchar,
    event_id       integer references event (id),
    commentator_id integer references users (id),
    date_create    timestamp,
    isPublished    varchar,
    constraint pk_comment primary key (id)
);